#ifndef __HW_PHYTIMER_H__
#define __HW_PHYTIMER_H__

//#include "hw_ints.h"
#include "xinyi2100.h"

//#include "hw_types.h"
//#include "interrupt.h"
//#include "gpio.h"
//*****************************************************************************
//
// The following are defines for Phy timer register address.
//
//*****************************************************************************
#define PHYTIMER_TMRL_CNT				(0x00 + PHYTIMER_BASE)
#define PHYTIMER_TMRM_CNT				(0x02 + PHYTIMER_BASE)
#define PHYTIMER_TMRH_CNT				(0x04 + PHYTIMER_BASE)

#define PHYTIMER_TMRL_RLD				(0x08 + PHYTIMER_BASE)
#define PHYTIMER_TMRM_RLD				(0x0A + PHYTIMER_BASE)
#define PHYTIMER_TMRH_RLD				(0x0C + PHYTIMER_BASE)

#define PHYTIMER_TMRL_OFFSET			(0x10 + PHYTIMER_BASE)
#define PHYTIMER_TMRM_OFFSET			(0x12 + PHYTIMER_BASE)									
#define PHYTIMER_TMRH_OFFSET			(0x14 + PHYTIMER_BASE)

#define PHYTIMER_CTL					(0x18 + PHYTIMER_BASE)	
#define PHYTIMER_STAT					(0x1A + PHYTIMER_BASE)
#define PHYTIMER_INT_STAT				(0x1C + PHYTIMER_BASE)
#define PHYTIMER_INT_ENA				(0x1E + PHYTIMER_BASE)
#define PHYTIMER_SNAPF					(0x20 + PHYTIMER_BASE)

#define PHYTIMER_TRX0_CFG_CTL			(0x24 + PHYTIMER_BASE)
#define PHYTIMER_TRX1_CFG_CTL			(0x25 + PHYTIMER_BASE)
#define PHYTIMER_TRX2_CFG_CTL			(0x26 + PHYTIMER_BASE)
#define PHYTIMER_TRX3_CFG_CTL			(0x27 + PHYTIMER_BASE)

#define PHYTIMER_TRX0_CFG_CNT			(0x28 + PHYTIMER_BASE)

#define PHYTIMER_TMRL_SNAPSHOT			(0x2C + PHYTIMER_BASE)
#define PHYTIMER_TMRM_SNAPSHOT			(0x2E + PHYTIMER_BASE)
#define PHYTIMER_TMRH_SNAPSHOT			(0x30 + PHYTIMER_BASE)

#define PHYTIMER_DFECLKPHSADJ			(0x34 + PHYTIMER_BASE)

#define PHYTIMER_SFW1_CFG_CNT			(0x38 + PHYTIMER_BASE)
#define PHYTIMER_SFW2_CFG_CNT			(0x3C + PHYTIMER_BASE)

#define PHYTIMER_TRX1_CFG_CNT			(0x40 + PHYTIMER_BASE)
#define PHYTIMER_TRX2_CFG_CNT			(0x44 + PHYTIMER_BASE)
#define PHYTIMER_TRX3_CFG_CNT			(0x48 + PHYTIMER_BASE)

#define PHYTIMER_TMRL_DIR_Pos			15
#define	PHYTIMER_TMRL_DIR_Msk			(1UL << PHYTIMER_TMRL_DIR_Pos)

#define PHYTIMER_TMRM_DIR_Pos			7
#define	PHYTIMER_TMRM_DIR_Msk			(1UL << PHYTIMER_TMRM_DIR_Pos)

#define PHYTIMER_TMRH_DIR_Pos			23
#define	PHYTIMER_TMRH_DIR_Msk			(1UL << PHYTIMER_TMRH_DIR_Pos)

#define PHYTIMER_ENA_Pos				0
#define PHYTIMER_ENA_Msk				(1UL << PHYTIMER_ENA_Pos)
#define PHYTIMER_UTC_ALARM_EN_Pos		1
#define PHYTIMER_UTC_ALARM_EN_Msk		(1UL << PHYTIMER_UTC_ALARM_EN_Pos)

#define PHYTIMER_UTC_ALARM_RESET_Pos	2
#define PHYTIMER_UTC_ALARM_RESET_Msk		(1UL << PHYTIMER_UTC_ALARM_RESET_Pos)

#define PHYTIMER_TMRL_POL_Pos			6
#define PHYTIMER_UTC_ALARM_EN_Msk		(1UL << PHYTIMER_UTC_ALARM_EN_Pos)


#define PHYTIMER_TMRL_INT_EN_Pos		0
#define PHYTIMER_TMRL_INT_EN_Msk		(1UL << PHYTIMER_TMRL_INT_EN_Pos)
#define PHYTIMER_TMRM_INT_EN_Pos		1
#define PHYTIMER_TMRM_INT_EN_Msk		(1UL << PHYTIMER_TMRM_INT_EN_Pos)
#define PHYTIMER_TMRH_INT_EN_Pos		2
#define PHYTIMER_TMRH_INT_EN_Msk		(1UL << PHYTIMER_TMRH_INT_EN_Pos)
#define PHYTIMER_TRX0MATCH_INT_EN_Pos	3
#define PHYTIMER_TRX0MATCH_INT_EN_Msk	(1UL << PHYTIMER_TRX0MATCH_INT_EN_Pos)
#define PHYTIMER_TRX1MATCH_INT_EN_Pos	4
#define PHYTIMER_TRX1MATCH_INT_EN_Msk	(1UL << PHYTIMER_TRX1MATCH_INT_EN_Pos)
#define PHYTIMER_TRX2MATCH_INT_EN_Pos	5
#define PHYTIMER_TRX2MATCH_INT_EN_Msk	(1UL << PHYTIMER_TRX2MATCH_INT_EN_Pos)
#define PHYTIMER_TRX3MATCH_INT_EN_Pos	6
#define PHYTIMER_TRX3MATCH_INT_EN_Msk	(1UL << PHYTIMER_TRX3MATCH_INT_EN_Pos)
#define PHYTIMER_SFW1MATCH_INT_EN_Pos	7
#define PHYTIMER_SFW1MATCH_INT_EN_Msk	(1UL << PHYTIMER_SFW1MATCH_INT_EN_Pos)

#define PHYTIMER_SFW2MATCH_INT_EN_Pos	8
#define PHYTIMER_SFW2MATCH_INT_EN_Msk	(1UL << PHYTIMER_SFW2MATCH_INT_EN_Pos)

//#define PHYTIMER_HW_TRX_ENA_Pos			0
//#define PHYTIMER_HW_TRX_ENA_Msk			(3UL << PHYTIMER_HW_TRX_ENA_Pos)

#define PHYTIMER_CNT_ENA_Pos			0
#define PHYTIMER_CNT_ENA_Msk			(1UL << PHYTIMER_CNT_ENA_Pos)
#define PHYTIMER_HW_TRX_EN_Pos			1
#define PHYTIMER_HW_TRX_EN_Msk			(1UL << PHYTIMER_HW_TRX_EN_Pos)

#define PHYTIMER_TMRL_INT_STAT_Pos		0
#define PHYTIMER_TMRL_INT_STAT_Msk		(1UL << PHYTIMER_TMRL_INT_STAT_Pos)
#define PHYTIMER_TMRM_INT_STAT_Pos		1
#define PHYTIMER_TMRM_INT_STAT_Msk		(1UL << PHYTIMER_TMRM_INT_STAT_Pos)
#define PHYTIMER_TMRH_INT_STAT_Pos		2
#define PHYTIMER_TMRH_INT_STAT_Msk		(1UL << PHYTIMER_TMRH_INT_STAT_Pos)
#define PHYTIMER_TRX0MATCH_INT_STAT_Pos	3
#define PHYTIMER_TRX0MATCH_INT_STAT_Msk	(1UL << PHYTIMER_TRX0MATCH_INT_STAT_Pos)
#define PHYTIMER_TRX1MATCH_INT_STAT_Pos	4
#define PHYTIMER_TRX1MATCH_INT_STAT_Msk	(1UL << PHYTIMER_TRX1MATCH_INT_STAT_Pos)
#define PHYTIMER_TRX2MATCH_INT_STAT_Pos	5
#define PHYTIMER_TRX2MATCH_INT_STAT_Msk	(1UL << PHYTIMER_TRX2MATCH_INT_STAT_Pos)
#define PHYTIMER_TRX3MATCH_INT_STAT_Pos	6
#define PHYTIMER_TRX3MATCH_INT_STAT_Msk	(1UL << PHYTIMER_TRX3MATCH_INT_STAT_Pos)

#define PHYTIMER_SFW1MATCH_INT_STAT_Pos	7
#define PHYTIMER_SFW1MATCH_INT_STAT_Msk	(1UL << PHYTIMER_SFW1MATCH_INT_STAT_Pos)
#define PHYTIMER_SFW2MATCH_INT_STAT_Pos	8
#define PHYTIMER_SFW2MATCH_INT_STAT_Msk	(1UL << PHYTIMER_SFW2MATCH_INT_STAT_Pos)

#endif

